version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: core/docker/Dockerfile
    ports:
      - "8000:8000"  # Adjust port if needed
    networks:
      - my_network

  frontend:
    build:
      context: .
      dockerfile: frontend/docker/Dockerfile
    ports:
      - "80:80"  # Adjust port if needed
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
